config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :blog_posts, :path => 'blogposts'

  get "home/index"
  get 'home/newaction' => 'blog_posts#index'

  get ':title/p/:id' => 'blog_posts#show', :id => /[0-9]+/

  post 'blogposts/comment' => 'blog_posts#comment'

  root :to => 'home#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :content, :publishdate, :title, :ispublished

  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :blog_post_id, :comment, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all

    if user_signed_in?
      render
    else
      render 'home/index'
    end
  end

  # POST /comment
  def comment
    @comment = Comment.new(params[:comment])

    unless @comment.save
      flash[:comment_errors] = @comment.errors.full_messages
    end

    redirect_to blog_post_path(@comment.blog_post_id)
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    authenticate_user!

    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    authenticate_user!

    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    authenticate_user!

    @blog_post = BlogPost.new(params[:blog_post])

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render json: @blog_post, status: :created, location: @blog_post }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    authenticate_user!

    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    authenticate_user!

    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blog_posts = BlogPost.where(:ispublished => true).order('publishdate desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :disabled => readonly ||= false %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content, :disabled => readonly ||= false %>
  </div>
  <div class="field">
    <%= f.label :publishdate %><br />
    <%= f.datetime_select :publishdate, :disabled => readonly ||= false %>
  </div>
  <div class="field">
    Is Published? <br />
    <%= f.check_box :ispublished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form', :readonly => false %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Listing blog_posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Publishdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% content_for :header do %>
      <p> Blog post index</p>
  <% end %>

<% @blog_posts.each do |blog_post| %>
  <tr>
    <td><%= blog_post.title %></td>
    <td><%= blog_post.content %></td>
    <td><%= blog_post.publishdate %></td>
    <td><%= link_to 'Show', blog_post %></td>
    <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
    <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @blog_post.title %></h2>
  <%= @blog_post.publishdate.strftime('%Y-%m-%d %I:%M')%>
</p>
<p>
  <%= @blog_post.content%>
</p>
<p>
  <br/>
</p>
<% unless current_user.nil? %>
    <h3>Leave A Comment</h3>
    <%= form_tag('/blogposts/comment') do %>
        <%= label_tag 'Email: '.concat(current_user.email) %><br/>
        <%= hidden_field_tag 'comment[email]', current_user.email %><br/>
        <%= label_tag 'Comment:' %><br/>
        <%= text_area_tag 'comment[comment]', ''%><br/>
        <%= hidden_field_tag 'comment[blog_post_id]', @blog_post.id %>
        <%= submit_tag 'Post' %>
    <% end %>
<% end %>
<h3>Comments</h3>
<% @blog_post.comments.each do |c| %>
    <p>
      <%= "#{c.email} #{c.created_at.strftime('%Y-%m-%d %I:%M')}"%><br/>
      <%= c.comment %>
    </p>
<% end %>
<%= link_to 'Edit', edit_blog_post_path(@blog_post) if user_signed_in? %> |
<%= link_to 'Back', blog_posts_path %>

app/views/home/index.html.erb
<% @blog_posts.each do |p| %>
    <p>
      <h2><%=link_to p.title, p %></h2>
      <%= p.content[0...100]%>
    </p>
<% end %>

app/views/layouts/_usermenu.html.erb
<% if user_signed_in? %>
    <%= link_to 'Log out', destroy_user_session_path, :method => 'delete' %>
    <%= link_to 'Create', new_blog_post_path %>
    <%= link_to 'List', blog_posts_path %>
<% else %>
    <%= link_to 'Log in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="usermenu">
  <%= render 'layouts/usermenu' %>
</div>
<%= image_tag 'rails.png' %>

<% if content_for? :header %>
    <%= yield :header %>
<% else %>
    <h1>Welcome to Crog, Crappy Blog</h1>
<%end%>
<%= yield %>

</body>
</html>